name: iospush
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  go_router: ^14.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
