// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRRe791Z35IhbcMB4PFANP15JuQCYwVg',
    appId: '1:225534267057:web:ee301183e2f8c2469b9c90',
    messagingSenderId: '225534267057',
    projectId: 'push-ios-prueba',
    authDomain: 'push-ios-prueba.firebaseapp.com',
    storageBucket: 'push-ios-prueba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgaBZwbjsfkC3ue5nxJnCp66kAQ9K1MJ8',
    appId: '1:225534267057:android:014961cf3700e1a69b9c90',
    messagingSenderId: '225534267057',
    projectId: 'push-ios-prueba',
    storageBucket: 'push-ios-prueba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7YKwM8Unq_HxnqopS3YYsZKKfIJQmsq0',
    appId: '1:225534267057:ios:758a16a8488b5ac69b9c90',
    messagingSenderId: '225534267057',
    projectId: 'push-ios-prueba',
    storageBucket: 'push-ios-prueba.appspot.com',
    iosBundleId: 'com.gertcode.iospush',
  );
}
